"""初始化测试用例示例数据"""
import asyncio
from datetime import datetime, timedelta

from database import async_session_maker, init_db
from models_test_case import TestCase, CasePriority, CaseStatus, CaseType


async def seed_test_cases():
    """填充测试用例示例数据"""
    await init_db()
    
    async with async_session_maker() as session:
        from sqlalchemy import select
        result = await session.execute(select(TestCase))
        existing = result.scalars().first()
        if existing:
            print("测试用例数据已存在，跳过初始化")
            return
        
        test_cases = [
            TestCase(
                name="用户登录接口测试",
                description="验证用户使用正确凭据登录系统的功能",
                case_type=CaseType.API,
                priority=CasePriority.P0,
                status=CaseStatus.ACTIVE,
                directory_id=1,
                module="登录模块",
                preconditions="用户账号状态正常，未被锁定",
                test_steps="1. 输入正确的用户名\n2. 输入正确的密码\n3. 点击登录按钮",
                expected_results="登录成功，跳转到首页，显示用户信息",
                author="张三",
                tags="登录,认证,API,P0",
                total_runs=120,
                passed_runs=118,
                failed_runs=2,
                last_run_time=datetime.utcnow() - timedelta(hours=2),
                avg_duration=1.5,
                is_automated=True,
                is_parallel=True,
                flaky=False,
            ),
            TestCase(
                name="用户注册接口测试",
                description="验证新用户可以成功注册账号",
                case_type=CaseType.API,
                priority=CasePriority.P0,
                status=CaseStatus.ACTIVE,
                directory_id=1,
                module="注册模块",
                preconditions="注册邮箱未被使用",
                test_steps="1. 输入有效的邮箱地址\n2. 输入符合规范的密码\n3. 确认密码\n4. 点击注册按钮",
                expected_results="注册成功，发送验证邮件到邮箱",
                author="张三",
                tags="注册,认证,API,P0",
                total_runs=95,
                passed_runs=93,
                failed_runs=2,
                last_run_time=datetime.utcnow() - timedelta(hours=5),
                avg_duration=2.3,
                is_automated=True,
                is_parallel=True,
                flaky=False,
            ),
            TestCase(
                name="商品列表查询接口",
                description="验证分页查询商品列表功能正常",
                case_type=CaseType.API,
                priority=CasePriority.P1,
                status=CaseStatus.ACTIVE,
                directory_id=2,
                module="商品模块",
                preconditions="系统中存在至少50个商品数据",
                test_steps="1. 调用商品列表接口\n2. 设置page=1, page_size=20\n3. 验证返回数据结构",
                expected_results="返回20条商品记录，包含分页信息",
                author="李四",
                tags="商品,查询,分页,P1",
                total_runs=80,
                passed_runs=80,
                failed_runs=0,
                last_run_time=datetime.utcnow() - timedelta(hours=1),
                avg_duration=0.8,
                is_automated=True,
                is_parallel=True,
                flaky=False,
            ),
            TestCase(
                name="商品详情页 UI 渲染",
                description="验证商品详情页面元素正确渲染",
                case_type=CaseType.UI,
                priority=CasePriority.P1,
                status=CaseStatus.ACTIVE,
                directory_id=2,
                module="商品前端",
                preconditions="商品 ID=1001 存在且有完整的图片和描述",
                test_steps="1. 打开商品详情页\n2. 验证商品名称显示\n3. 验证图片加载\n4. 验证价格显示\n5. 验证购买按钮可见",
                expected_results="所有元素正确渲染，无样式错乱",
                author="王五",
                tags="UI,商品详情,前端,P1",
                total_runs=45,
                passed_runs=42,
                failed_runs=3,
                last_run_time=datetime.utcnow() - timedelta(days=1),
                avg_duration=5.2,
                is_automated=True,
                is_parallel=False,
                flaky=True,
            ),
            TestCase(
                name="购物车添加商品",
                description="验证用户可以将商品添加到购物车",
                case_type=CaseType.API,
                priority=CasePriority.P0,
                status=CaseStatus.ACTIVE,
                directory_id=3,
                module="购物车模块",
                preconditions="用户已登录，商品库存充足",
                test_steps="1. 调用添加购物车接口\n2. 传入商品ID和数量\n3. 查询购物车列表验证",
                expected_results="商品成功添加到购物车，数量正确",
                author="李四",
                tags="购物车,商品,API,P0",
                total_runs=150,
                passed_runs=148,
                failed_runs=2,
                last_run_time=datetime.utcnow() - timedelta(hours=3),
                avg_duration=1.2,
                is_automated=True,
                is_parallel=True,
                flaky=False,
            ),
            TestCase(
                name="订单创建流程 E2E",
                description="端到端测试：完整的下单流程",
                case_type=CaseType.E2E,
                priority=CasePriority.P0,
                status=CaseStatus.ACTIVE,
                directory_id=3,
                module="订单模块",
                preconditions="用户已登录，购物车有商品，地址已设置",
                test_steps="1. 进入购物车\n2. 选择商品\n3. 确认订单信息\n4. 选择配送地址\n5. 选择支付方式\n6. 提交订单",
                expected_results="订单创建成功，生成订单号，跳转支付页面",
                author="赵六",
                tags="订单,E2E,核心流程,P0",
                total_runs=60,
                passed_runs=58,
                failed_runs=2,
                last_run_time=datetime.utcnow() - timedelta(hours=8),
                avg_duration=15.5,
                is_automated=True,
                is_parallel=False,
                flaky=False,
            ),
            TestCase(
                name="密码重置功能",
                description="验证用户可以通过邮箱重置密码",
                case_type=CaseType.API,
                priority=CasePriority.P1,
                status=CaseStatus.ACTIVE,
                directory_id=1,
                module="安全模块",
                preconditions="用户已绑定邮箱",
                test_steps="1. 点击忘记密码\n2. 输入注册邮箱\n3. 点击发送重置链接\n4. 打开邮件中的链接\n5. 设置新密码",
                expected_results="密码重置成功，可使用新密码登录",
                author="孙七",
                tags="密码,安全,邮箱,P1",
                total_runs=70,
                passed_runs=68,
                failed_runs=2,
                last_run_time=datetime.utcnow() - timedelta(days=2),
                avg_duration=3.8,
                is_automated=False,
                is_parallel=False,
                flaky=False,
            ),
            TestCase(
                name="搜索功能高并发压测",
                description="验证搜索接口在并发请求下的性能表现",
                case_type=CaseType.PERFORMANCE,
                priority=CasePriority.P2,
                status=CaseStatus.ACTIVE,
                directory_id=2,
                module="搜索模块",
                preconditions="索引中有10000+条数据",
                test_steps="1. 使用 JMeter 设置 100 并发\n2. 持续压测 5 分钟\n3. 监控响应时间和错误率",
                expected_results="平均响应时间 < 200ms，错误率 < 1%",
                author="周八",
                tags="性能,压测,并发,P2",
                total_runs=20,
                passed_runs=18,
                failed_runs=2,
                last_run_time=datetime.utcnow() - timedelta(days=3),
                avg_duration=300.0,
                is_automated=True,
                is_parallel=True,
                flaky=False,
            ),
            TestCase(
                name="用户登出接口测试",
                description="验证用户可以正常登出系统",
                case_type=CaseType.API,
                priority=CasePriority.P1,
                status=CaseStatus.ACTIVE,
                directory_id=1,
                module="登录模块",
                preconditions="用户已登录",
                test_steps="1. 调用登出接口\n2. 验证 session 清除\n3. 尝试访问需要认证的接口",
                expected_results="登出成功，session 失效",
                author="张三",
                tags="登出,认证,API,P1",
                total_runs=100,
                passed_runs=100,
                failed_runs=0,
                last_run_time=datetime.utcnow() - timedelta(hours=6),
                avg_duration=0.5,
                is_automated=True,
                is_parallel=True,
                flaky=False,
            ),
            TestCase(
                name="库存扣减接口",
                description="验证下单时库存正确扣减",
                case_type=CaseType.API,
                priority=CasePriority.P0,
                status=CaseStatus.ACTIVE,
                directory_id=2,
                module="库存模块",
                preconditions="商品库存为100件",
                test_steps="1. 调用库存扣减接口\n2. 扣减数量为5\n3. 查询库存验证",
                expected_results="库存正确扣减为95件",
                author="李四",
                tags="库存,扣减,事务,P0",
                total_runs=88,
                passed_runs=85,
                failed_runs=3,
                last_run_time=datetime.utcnow() - timedelta(hours=4),
                avg_duration=2.1,
                is_automated=True,
                is_parallel=False,
                flaky=True,
            ),
            TestCase(
                name="邮件通知服务",
                description="验证系统事件触发邮件通知",
                case_type=CaseType.API,
                priority=CasePriority.P2,
                status=CaseStatus.DRAFT,
                directory_id=4,
                module="通知模块",
                preconditions="邮件服务配置正常",
                test_steps="1. 触发订单创建事件\n2. 检查邮件发送队列\n3. 验证邮件内容",
                expected_results="邮件成功发送，内容正确",
                author="吴九",
                tags="邮件,通知,异步,P2",
                total_runs=15,
                passed_runs=12,
                failed_runs=3,
                last_run_time=datetime.utcnow() - timedelta(days=5),
                avg_duration=4.5,
                is_automated=False,
                is_parallel=True,
                flaky=False,
            ),
            TestCase(
                name="数据导出功能",
                description="验证用户可以导出数据为 Excel",
                case_type=CaseType.API,
                priority=CasePriority.P3,
                status=CaseStatus.DEPRECATED,
                directory_id=5,
                module="报表模块",
                preconditions="有足够的报表数据",
                test_steps="1. 选择导出条件\n2. 点击导出按钮\n3. 下载 Excel 文件",
                expected_results="Excel 文件正确生成，数据完整",
                author="郑十",
                tags="导出,Excel,报表,P3",
                total_runs=25,
                passed_runs=24,
                failed_runs=1,
                last_run_time=datetime.utcnow() - timedelta(days=10),
                avg_duration=8.2,
                is_automated=False,
                is_parallel=False,
                flaky=False,
            ),
        ]
        
        session.add_all(test_cases)
        await session.commit()
        print("测试用例示例数据初始化完成")


if __name__ == "__main__":
    asyncio.run(seed_test_cases())
